[package]
name = "fun8s-lite"
version = "0.1.0"
authors = ["moss"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmd_lib = "0.7.8"